### ISSUE TITLE
[Feature Request] QwikCity Support

### ISSUE THREAD

**Issue by RumNCodeDev** [ProNextJS/declarative-routing#11]
I have made some changes to get this package working in **QwikCity**.
## Working
- Commands
  - `init`
  - `build`
  - `build --watch`
- What works
  - Build routes for pages in the `src/routes` directory. This includes adding `params` and `searchParams` as well. 

## Not Yet Working
- API Routes
  - ie `GET`/`PUT`/`POST`/`DELETE`. 

I had to update the `build` command to go through and determine which `build` command to use, as the code was only setup to use the `next` build command as it was. 

You can take a look at my changes here.
https://github.com/RumNCodeDev/declarative-routing

I placed them all in a single commit located [here](https://github.com/RumNCodeDev/declarative-routing/commit/89e67637becbbeeb342c28acfe51d06594b5bbde)

I will probably also have to update the dependency checks to handle the `Qwik V2` as that will have a different import as they are moving out of the `@builder.io` repo, and into its own repo for `v2`.

**Comment by RumNCodeDev** [comment]
I think i might need to make a slight change to get routes that used [named layouts](https://qwik.dev/docs/advanced/routing/#named-layout) supported as well. Just need to update it from only `index.tsx` to also search for index`@something`.tsx as well

**Comment by jherr** [comment]
If the idea is that you'd just export from `page.tsx` or `route.tsx` directly, NextJS doesn't allow exporting anything it doesn't know about from those files. And also it would break code splitting since routes would hard link to all the routes and pages.

**Comment by RumNCodeDev** [comment]
This fork that I stubbed out would not be for use with NextJS, this would be to add a 3rd option, and to have Delcarative Routing feature for a project built with Qwik/QwikCity. I do not believe it should affect any of the existing code for NextJS/React-Router-Dom as its just adding a 3rd option, unless I am mistaken.

**Comment by jherr** [comment]
I've got no problem with that. Let's add support for Qwik City.

**Comment by RumNCodeDev** [comment]
Awesome, glad to hear it. I have to update the readme a bit more, add support for named layouts, and then should be good aside from maybe trying to figure out the api routes.

**Comment by RumNCodeDev** [comment]
Darn... that `shared` refactor that happened just recently will require me to make a lot of changes.. Oh well.. just gotta knock them out i suppose

**Comment by jherr** [comment]
Sorry. We just moved a few things into a shared folder. And the NextJS version went through some decent changes.

**Comment by RumNCodeDev** [comment]
No worries, obviously everybody wants whats best for the project overall. Its my fault for being slow to get this knocked out
