### ISSUE TITLE
With NextJS 14.2 version unable to build

### ISSUE THREAD

**Issue by Virous77** [ProNextJS/declarative-routing#22]
**I just upgraded my app to latest Next.J version(14.2) but when i started dev server i got this error.**

![Image 18-04-24 at 12 26 AM](https://github.com/ProNextJS/declarative-routing/assets/101452588/eea6263d-f147-4800-b5e9-aca6335b1d16)

![Image 18-04-24 at 12 29 AM](https://github.com/ProNextJS/declarative-routing/assets/101452588/e00c1b99-5e5c-4082-9eee-2e00be5bc656)

```
System:
OS: macOS 14.2.1
CPU: (8) arm64 Apple M1
Memory: 78.80 MB / 8.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
Yarn: 1.22.21 - ~/Desktop/Personal-Projects/Reetesh/frontend/node_modules/.bin/yarn
npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
Browsers:
Brave Browser: 120.1.61.116
Chrome: 120.0.6099.234
Firefox: 121.0.1
Safari: 17.2.1
```

**Comment by jherr** [comment]
You are running an older version of the code. Please re-initialize with the latest version, or copy and paste the `makeRoutes.tsx` and `hooks.ts` files from the `/assets/nextjs` directory in this project.

**Comment by Virous77** [comment]
That works.
