### ISSUE TITLE
Automatic route detection for file-based routers

### ISSUE THREAD

**Issue by kpervin** [ProNextJS/declarative-routing#24]
Would it make any sense to potentially have automatic path detection? I created a script that may be useful on build:

```ts
async function getCurrentFileRoute(): Promise<string> {
  const path = await import("path");
  const { dir, name } = path.parse(__filename);
  /**
   * We split first then recombine so that we have bash/cmd/pwsh agnosticism
   */
  const separatedPath = dir.split(path.sep);
  const formattedDirPath = `/${separatedPath
    .slice(separatedPath.indexOf(".next") + 3) /* Path always resolves to ~/.next/server/(app|pages)/... */
    .join("/")}`;
  /**
   * If root of app/pages directory, return '/'
   */
  if (/^(pages|app)$/.test(formattedDirPath)) {
    return `/`;
  }
  /**
   * If we reach a file that is not indicative of a route,
   * return parent directory path as route
   */
  if (/(page|index|layout|routedef)/.test(name)) {
    return `${formattedDirPath}`;
  }
  /**
   * Return file route (mainly pages dir compatibility)
   */
  return `${formattedDirPath}/${name}`;
}
```

This way, if `makeRoute` is defined within the pages router, we can include it in the file that would also house `getServerSideProps` and etc, and in the app router it could be an independent file called `routedef` or included in `page` or `layout`.

This would mostly be for any frameworks that use file-based routing, and in this case it would be NextJS.

**Comment by jherr** [comment]
I'm happy to support the Pages router as well. I'm not sure how this fits into that though. Can you put together a PR?

**Comment by jherr** [comment]
`makeRoute` is called in the `index.ts` file of `@/routes` to build a route component for a given route. In NextJS it imports a `.info` file located in each route directory to get the biographic information for the route (name, params, search params, etc.)

You use the components created by `makeRoute` and exported by `@/routes` as replacements for `<Link>` components.

`makeRoute` doesn't actually make a route, it makes a route link component.

**Comment by kpervin** [comment]
Hmmm, gotcha. Reason I'm thinking along these lines has to do with refactoring in case you need to move routes around. That being said, it's not going to be a frequent occurrence, but would save some peace of mind being able to have the route defined in the same location as the file serving the route. Additionally for `get{Fn}Props` in the pages router it can reuse the Zod schemas for queries and params respectively. I'm not familiar enough with the app router to say if that would be beneficial or not in that scenario.

**Comment by kpervin** [comment]
@jherr I did but as said previously it's become apparent that I did not pay well enough attention 😅
My apologies for wasting your time with this.
