### ISSUE TITLE
Issue with Locale

### ISSUE THREAD

**Issue by d-sooter** [ProNextJS/declarative-routing#26]
I think there is an issue if you are using a [locale] route as the base 

ex: [locale]/dashboard 
gets rendered as 
 -> //dashboard
 
 
i ended up making a small change to the createPathBuilder function and adding a filter to remove empty strings before the join('/') but i havent spent a lot of time to check what other side effects show up. but it works for my usecase

`
function createPathBuilder<T extends Record<string, string | string[]>>(
  route: string
): (params: T) => string {

...

return (params: T): string => {
    const p = elems.map((e) => e(params)).filter(e => !!e).join("/");
    if (catchAllSegment) {
      return p + catchAllSegment(params);
    } else {
      return p;
    }
  };
}
`

**Comment by jherr** [comment]
What's the correct route with `/[locale]/dashboard`. Isn't `[locale]` a parameter?

**Comment by d-sooter** [comment]
Maybe this helps with some context.

https://locize.com/blog/next-app-dir-i18n/

**Comment by d-sooter** [comment]
Hi Jack.

The correct urls would be 
Undefined => /dashboard
ja-JP => /ja-JP/dashboard

**Comment by jherr** [comment]
Cool. Thank you. I'll get that fix in.

**Comment by spiftire** [comment]
Any progress regarding this issue?

**Comment by jherr** [comment]
Fixed in 0.1.20.
