### ISSUE TITLE
DELETE routes do not accept route.info.ts zod objects

### ISSUE THREAD

**Issue by JonBernardHealia** [ProNextJS/declarative-routing#30]
When creating a DELETE endpoint with declarative-routing, I'm getting a few errors.

It looks like `makeDeleteRoute` does not accept the `getInfo: GetInfo` argument, but the build process creates the route with the getInfo attached, and it errors.

<img width="653" alt="Screenshot 2024-05-29 at 2 37 13 PM" src="https://github.com/ProNextJS/declarative-routing/assets/114526470/636ff9c9-e026-48db-ace4-09c8344dd8a8">
<img width="772" alt="Screenshot 2024-05-29 at 2 36 54 PM" src="https://github.com/ProNextJS/declarative-routing/assets/114526470/8d0367d7-b52e-4b40-a3ce-0bc8fff1eb34">
<img width="279" alt="Screenshot 2024-05-29 at 2 38 08 PM" src="https://github.com/ProNextJS/declarative-routing/assets/114526470/9afb4024-f053-42ac-a757-ee8a45f288e8">

If `makeDeleteRoute` isn't supposed to accept this argument, that's fine, but it needs to not generate the route with the argument attached, and we need a way to indicate that it should generate a delete route. `export const DELETE = {};` does not work.

**Comment by JonBernardHealia** [comment]
It looks like this can be resolved by adding a conditional to the `index.ts.template` handlebars template.

`src/shared/build-tools.ts`
![build-tools](https://github.com/ProNextJS/declarative-routing/assets/114526470/741bf379-dc12-4abe-bd84-c5e4ab45dc76)

`assets/shared/index.ts.template`
![template](https://github.com/ProNextJS/declarative-routing/assets/114526470/1df21187-fc7a-4974-b081-a34c3315531c)

**Comment by jherr** [comment]
Looks good, feel free to PR.
