### ISSUE TITLE
Improve support for kebab-case naming convention

### ISSUE THREAD

**Issue by createdbymahmood** [ProNextJS/declarative-routing#31]
I've been using this package for a while now and integrated it into one of my projects. I encountered a small issue when generating files and would like to suggest an improvement for better support of kebab-case naming convention.

Here is the structure of my directory:

```bash
 ├── authentication
 │   ├── account-setup
 │   │   ├── account-info
 │   │   │   └── page.tsx
```

Based on the current version of declarative-routing, the generated `page.info.ts` would be named `AuthenticationAccountsetupAccountinfo`. It would be more meaningful if the package could generate something like `AuthenticationAccountSetupAccountInfo` instead.

I suggest modifying the jsClean function as follows:

```ts
export const jsClean = (str: string) => {
  // Clean all non-alphanumberic values except for dashes
  const cleanString = str.replace(/[^a-zA-Z0-9-]/g, "");

  // Capitalize the letter following a dash
  const capitalizedAfterDash = cleanString.replace(
    /-([a-zA-Z])/g,
    (_, letter) => letter.toUpperCase()
  );

  // Remove all dashes and non-alphanumeric characters
  return capitalizedAfterDash.replace(/[^a-zA-Z0-9]/g, "");
};
```

If this suggestion is confirmed, I would be happy to send a pull request with the necessary changes.
Thank you!

**Comment by jherr** [comment]
Go for it! Sounds great!
