### ISSUE TITLE
[Feature Request] Separate generated and static code for a non-vcs approach?

### ISSUE THREAD

**Issue by hedefalk** [ProNextJS/declarative-routing#36]
First off, thank you for this project!

I was just struggling with building something to get rid of all the "magic strings" that break at times in our nextui project and found this. There is really good stuff here!

I guess my request is non-negotiable, because it seems you really want to go the chadcn approach, but I thought I should ask anyway :)

Thing is, for my purposes, version controlling generated code that might update pretty often is just a hard no. Gun threat hard. I'm struggling with this all the time in the js world where scaffolding is more and more common. Some scaffolding can be okay, but I couldn't find a way to use this project as is without too much smell in our project.

Thing is - I have a monorepo with multiple next.js apps. Using this as I think I understand is described would force me into version controlling multiple copies of the exact same "static" code, that is:

* hooks.ts
* makeRoute.tsx

Or rather either that or doing really involved .gitignore blobs to just ignore those and not the "online generated" index.js with the actual routes and that README.md.

What I would really want is to have a project just like this, but that I install as a dev dependency (where the static part is placed (hooks, makeRoute and binaries), then add a postinstall script to run it on install where the output is put in a "generated" folder that is separate and easy to gitignore. 

That's how I typically would have codegen plugins work, like building protobuf or openapi or such. Static glue code in the library itself and generated code clearly separated and gitignored. That way codegen is just a higher level compilation and no burden. The .info files can be put in src as a side-effect I guess, as the only scaffolded part. 

Right now, I'm just going to take the hooks.ts and makeRoute.tsx files, put them in an aux package used by the next apps and have the rest be manual work within the separate apps. I'd love to have the autogen work though, but I can't motivate it if I have to stick all that extra stuff into vcs.

I have full respect that the scope of this project is bigger than mine and I might also have misunderstood the docs and all that. Anyway, thanks for this project, I'm gonna follow it!

**Comment by jherr** [comment]
FWIW, this project was always about bringing visibility to the concept of declarative routing as opposed to being the canonical implementation of declarative routing. In that light this project has done exactly what it should; inspired you to say, "I need declarative routing" and then to take none/some/all of what's here and then to bend and shape it to your needs.

For example, we were recently talking about an Astro implementation and it would use exactly none of this code. But it would accomplish the same goals of DRY links and API access.
