### ISSUE TITLE
Route Groups not processed correctly

### ISSUE THREAD

**Issue by sfarrowGR** [ProNextJS/declarative-routing#5]
Hi,

I really like this so far.

I have discovered that if your NextJS app direction includes groups, the generated URLs do not generate correctly.

Groups -> https://nextjs.org/docs/app/building-your-application/routing/route-groups

In the docs example of (folderName).  If you use declarative-routing, it generates a URL that includes /(folderName)/theactualpageroute/

Somehow, we need to exclude that portion from the generated url.

**Comment by jherr** [comment]
Fixed in 0.1.5.
