### ISSUE TITLE
[Feature request] Config option to use different path prefixes

### ISSUE THREAD

**Issue by lexwebb** [ProNextJS/declarative-routing#7]
My NextJs app is inside a monorepo where we have a specific typescript path configuration. We use `@name` for external paths and `#name` for internal (in next app) paths. 

At the moment this is causing issues as the auto generated `routes/index.ts` file uses `@/name` imports for the project. The ideal fix for this would be the ability to specify a prefix character.

I'd be happy to work on and raise a PR for this if you think this would be a helpful addition.

**Comment by lexwebb** [comment]
Scratch that - I found the config option, would be good to get these documented in the README. I'll raise a PR for that instead

**Comment by jherr** [comment]
Totally down with the change, and certainly adding more info to the README. But could you give me a little backstory on the use case here? What does this enable?

**Comment by xela92** [comment]
> There's no need for a change after all, there's an undocumented config option already in place that fulfils the needs of my project: `importPathPrefix`.
> 
> The only thing that would be good to change is to document all the options that can go into the config file.

It has been documented in the generated README file, but of course you have already init'ed the project and so can't see the new info (you can see what happened [here](https://github.com/ProNextJS/declarative-routing/pull/3)).

@jherr the templates are a great approach but feels like it's a pain to keep 'em up-to-date, and to keep main project's readme synced, we might need to find a better approach to keep things simple 😅

**Comment by jherr** [comment]
I'm all ears. My intention was that you'd do the conversion and then delete the `DR-README` or migrate parts of it into your app's style guide.

**Comment by lexwebb** [comment]
Thanks for the context. I have to say, I'm not sure I noticed that particular README file, it's possible i deleted it when i saw it in my diff. I'm used to seeing config/API docs in a packages repository README, maybe it should live in both?

**Comment by jherr** [comment]
Oh, yeah, actually, that's a great idea. I'll move it.

**Comment by jherr** [comment]
Moved the README file. I think this is closed now.
