### ISSUE TITLE
No longer works in RSCs in Next.js 14.2.0

### ISSUE THREAD

**Issue by novascreen** [ProNextJS/declarative-routing#9]
I don't know if this is a bug or intended behaviour in the new version of Next.js, but I'm now getting an error about the `useParams` import even if i just use `MyRoute.Link` in a React Server Component.

I've made a repro here: https://codesandbox.io/p/devbox/ecstatic-microservice-pltxks

I realize we can't use `useParams` in RSCs and Next wants to prevent us from doing the wrong thing, but this will make it really challenging to build tools like this. Before this new version Next only warned us when we actually used it, which should be enough imo.

Do you have an idea on how we get around this?

**Comment by novascreen** [comment]
Haha, yeah unfortunate timing. It's great that you did it though, more people need to be aware how much better Next.js' routing could be with proper types. Thank you!

I've build a similar utility (without the magic path updates you have built) and the way i've solved it for myself for now is to have a `useRouteParams` hook that takes the route info object. It means an extra import, but it isn't tooo painful.

```ts
const params = MyRoute.useParams()
// changes to
const params = useRouteParams(MyRoute)
```

**Comment by jherr** [comment]
Fixed in the most recent version. I went with your idea of doing `usePush(route)`, `useParams(route)` and `useSearchParams(route)`.
